name: cbse_math_app
description: "CBSE Class 10 Math App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_math_fork: ^0.7.2
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true